starbase/tawk-%f
starbase/utillib/CVS
starbase/CVS
starbase/bin/CVS
starbase/bsd/CVS
starbase/config/CVS
starbase/doc/CVS
starbase/doc/RCS
starbase/gnu/CVS
starbase/gnu/bin/CVS
starbase/gnu/doc/CVS
starbase/gnu/lib/CVS
starbase/gnu/man/CVS
starbase/gnu/src/CVS
starbase/gsc/CVS
starbase/include/CVS
starbase/iraf/CVS
starbase/lib/CVS
starbase/saocat/CVS
starbase/slalib/CVS
starbase/tablefun/CVS
starbase/tablelib/CVS
starbase/tablesrc/CVS
starbase/tawk/CVS
starbase/tawk/atarist/CVS
starbase/tawk/config-user/CVS
starbase/tawk/examples/CVS
starbase/tawk/man/CVS
starbase/tawk/msdos/CVS
starbase/tawk/msdos/examples/CVS
starbase/tawk/rexp/CVS
starbase/tawk/test/CVS
starbase/tawk/v7/CVS
starbase/test
starbase/iraf/src/CVS/
starbase/iraf/bin.ssol/CVS/
starbase/iraf/bin/CVS/
starbase/iraf/lib/CVS/
starbase/iraf/bin.ssun/CVS/
starbase/slalink/CVS/
starbase/slalink/examples/CVS/
starbase/test
starbase/gsc/junk/
starbase/tablesrc/junk/
starbase/tablelib/junk/

starbase/tawk/rexp-reg/
