#!/bin/sh
#
# coltorowtable
#
# Starbase Data Tables  - An Ascii Database for UNIX
#
#   copyright 2000 John B. Roll jr.
#   
PATH=.:/bin:/usr/bin;	export PATH

trap "" 13

 column -N _Number $1 | transposetable | column _Number:x

