#!/bin/sh
#
# fun3dtable - Run a function over each column of the input tables
#
# Starbase Data Tables  - An Ascii Database for UNIX
#
#   copyright 2000 John B. Roll jr.
#   
PATH=.:/bin:/usr/bin;	export PATH

trap "" 13

  if [ $# = 0 ] ; then
	echo "fun3dtable <function> [-f program] [column [column]... --] table [table...]" 1>&2
	exit 1
  fi

    fun=$1
    shift

  Break=`awk '
	BEGIN {
	    for ( i = 1; i < ARGC; i++ ) {
		if ( ARGV[i] == "--" ) { print "1"; exit(0) }
	    }
	}
    ' "$@"`


    if [ "$Break" = "1" ] ; then
        Break=""
	while [ $# -gt 0 ] ; do
	    case $1 in
	     -f)	Func=$2; shift		;;
	     --)	Break=1; shift; break	;;
	     *)	Cols="$Cols $1"		;;
	    esac
	    shift
	done

	if [ "$Break" = "" ] ; then
	    echo "usage : fun3table $fun [columns] -- files"	1>&2
	    exit 1
	fi
    else
	while [ $# -gt 0 ] ; do
	    case $1 in
	     -f)	Func=$2; shift		;;
	     -D)	D="-D"			;;
	     *)		break			;;
	    esac
	    shift
	done
    fi


    if [ "$1" = - ] ; then
	cat > $$.tmp
	shift
	set $$.tmp "$@"
    fi

    if [ "$Cols" = "" ] ; then
	Cols=`headline < $1`
    fi

    for Col in $Cols ; do
	Program="$Program 
		$Col = ${fun}3d(\"$Col\")"
    done

    if [ "$Func" != "" ] ; then 
        Func="-f $Func"
    fi

    compute3dtable $D $Func "$Program" "$@"

    rm $$.tmp
