#!/bin/sh
#
# funtotable
#
# Starbase Data Tables  - An Ascii Database for UNIX
#
#   copyright 1991, 1993, 1995, 1999 John B. Roll jr.
#
PATH=.:/bin:/usr/bin;	export PATH

	read HEADER
	read DASHES

	fldtotable $HEADER
