#!/bin/sh
#
# reseqtable
#
# Starbase Data Tables  - An Ascii Database for UNIX
#
#   copyright 1991, 1993, 1995, 1999 John B. Roll jr.
#   
PATH=.:/bin:/usr/bin;	export PATH

trap "" 13

 if [ $# != 1 ] ; then
 	echo "reseqtable <column>" 1>&2
	exit 1
 fi

 Column=$1

 compute "	__ST=$Column
		if ( $Column==__SN ) $Column =   __NS
	    	else		     $Column = ++__NS
	    	__SN=__ST"
