#!/bin/sh
#
# rttoxytable
#
# Starbase Data Tables  - An Ascii Database for UNIX
#
#   copyright 2000 John B. Roll jr.
#   
PATH=.:/bin:/usr/bin;	export PATH

trap "" 13


    if [ $# != 4 ] ; then
	echo "usage: rttoxytable r t x y < in.tab" 	1>&2
	exit 1
    fi

    R=$1
    T=$2
    X=$3
    Y=$4

      column -a $X $Y 			\
    | compute "[$X, $Y] = rttoxy($R, $T)"
