#!/bin/sh
#
# sextotable
#
# Starbase Data Tables  - An Ascii Database for UNIX
#
#   copyright 1991, 1993, 1995, 1999 John B. Roll jr.
#   
PATH=.:/bin:/usr/bin;	export PATH

trap "" 13

tawk '
    BEGIN	{ OFS="\t"; init = 0 }
    /^#/	{
		if ( init != 0 ) {
		    printf("\t")
		}
		init++
		printf("%s", $3)
		next
	    }
	    {
		if ( init > 0 ) {
		    print ""
		    init--
		    for ( i = 0; i < init; i++ ) { printf "-\t" }
		    print "-"
		    init = 0
		}
		for ( i = 1; i < NF; i++ )
		    printf $i "	"
		print $i
	    }
    END {
		if ( init > 1 ) {
		    print ""
		    init--
		    for ( i = 0; i < init; i++ ) { printf "-\t" }
		    print "-"
		    init = 0
		}
    }
'









