#!/bin/sh
#
# tabletohtml
#
# Starbase Data Tables  - An Ascii Database for UNIX
#
#   copyright 1991, 1993, 1995, 1999 John B. Roll jr.
#   
PATH=.:/bin:/usr/bin;	export PATH

trap "" 13

 echo "<table>"
 header -u -hl 						\
 | sed -e 's%^%<tr><td>%' -e 's%	%</td><td>%g' -e 's%$%</td>%'
   sed -e 's%^%<tr><td>%' -e 's%	%</td><td>%g' -e 's%$%</td>%'
 echo "</table>"
