
#line 3 "<stdout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 22
#define YY_END_OF_BUFFER 23
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[66] =
    {   0,
       23,   21,   22,   16,   21,   22,   13,   21,   22,   21,
       22,   21,   22,   21,   22,   12,   21,   22,    4,   21,
       22,   15,   22,   14,   22,   20,   22,   19,   20,   22,
       17,   20,   22,   18,   22,   22,   11,   22,   11,   22,
       10,   11,   22,    7,   22,    7,   22,    6,    7,   22,
        9,   21,   22,    8,   21,   22,    2,16387,    5,    4,
       10,    6,16387, 8195,    1
    } ;

static const flex_int16_t yy_accept[56] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    2,    4,    7,   10,   12,
       14,   16,   19,   22,   24,   26,   28,   31,   34,   36,
       37,   39,   41,   44,   46,   48,   51,   54,   57,   58,
       59,   59,   59,   60,   61,   61,   62,   62,   63,   63,
       64,   65,   65,   66,   66
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    6,
        1,    1,    7,    1,    8,    9,    1,   10,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,   12,    1,
       13,    1,    1,   14,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       16,   17,    1,    1,   15,    1,   15,   15,   15,   15,

       18,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[19] =
    {   0,
        1,    1,    2,    1,    1,    3,    4,    1,    1,    5,
        5,    1,    1,    1,    6,    1,    1,    7
    } ;

static const flex_int16_t yy_base[64] =
    {   0,
        0,    0,   55,   54,   15,   16,   53,   52,   19,   20,
       21,   22,   36,   47,   54,  138,  138,  138,   46,   10,
       34,  138,   45,  138,  138,  138,  138,  138,  138,  138,
      138,   24,  138,  138,   25,  138,  138,  138,  138,   51,
       29,   63,  138,   36,   27,  138,   28,  138,   21,   65,
       18,   35,  138,  138,   83,   90,   97,  104,  111,  115,
      118,  123,  130
    } ;

static const flex_int16_t yy_def[64] =
    {   0,
       54,    1,   55,   55,   56,   56,   57,   57,   58,   58,
       59,   59,    1,    1,   54,   54,   54,   54,   60,   54,
       61,   54,   62,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   63,
       61,   54,   54,   62,   54,   54,   54,   54,   63,   63,
       63,   54,   54,    0,   54,   54,   54,   54,   54,   54,
       54,   54,   54
    } ;

static const flex_int16_t yy_nxt[157] =
    {   0,
       16,   16,   16,   17,   18,   16,   19,   16,   20,   16,
       21,   16,   16,   22,   23,   16,   16,   23,   27,   27,
       32,   32,   35,   35,   40,   45,   47,   40,   45,   47,
       51,   28,   28,   51,   33,   33,   36,   36,   37,   46,
       48,   43,   46,   48,   53,   53,   42,   37,   38,   37,
       43,   42,   39,   54,   30,   30,   25,   25,   37,   38,
       50,   50,   54,   51,   54,   50,   54,   54,   50,   52,
       52,   54,   53,   53,   50,   50,   54,   51,   54,   50,
       54,   54,   50,   24,   24,   24,   24,   24,   24,   24,
       26,   26,   26,   26,   26,   26,   26,   29,   29,   29,

       29,   29,   29,   29,   31,   31,   31,   31,   31,   31,
       31,   34,   34,   34,   34,   34,   34,   34,   40,   54,
       40,   40,   41,   54,   41,   44,   54,   44,   44,   44,
       49,   54,   49,   49,   49,   49,   49,   15,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54
    } ;

static const flex_int16_t yy_chk[157] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    5,    6,
        9,   10,   11,   12,   20,   32,   35,   20,   45,   47,
       51,    5,    6,   49,    9,   10,   11,   12,   13,   32,
       35,   44,   45,   47,   52,   52,   41,   13,   13,   14,
       23,   21,   19,   15,    8,    7,    4,    3,   14,   14,
       40,   40,    0,   40,    0,   40,    0,    0,   40,   42,
       42,    0,   42,   42,   50,   50,    0,   50,    0,   50,
        0,    0,   50,   55,   55,   55,   55,   55,   55,   55,
       56,   56,   56,   56,   56,   56,   56,   57,   57,   57,

       57,   57,   57,   57,   58,   58,   58,   58,   58,   58,
       58,   59,   59,   59,   59,   59,   59,   59,   60,    0,
       60,   60,   61,    0,   61,   62,    0,   62,   62,   62,
       63,    0,   63,   63,   63,   63,   63,   54,   54,   54,
       54,   54,   54,   54,   54,   54,   54,   54,   54,   54,
       54,   54,   54,   54,   54,   54
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "table.l"
#line 2 "table.l"
/* table_lex.l
 */
/* Starbase Data Tables  - An Ascii Database for UNIX

   copyright 1991, 1993, 1995, 1999 John B. Roll jr.
 */

#include <xos.h>
#include <xfile.h>
#include <xlist.h>
#include "filelist.h"

#include <table.h>
#include <signal.h>

#define TABLEFUN	"$TABLEFUN:" TABLELIB "/tablefun"
#define TABLEINC	"$HOME:$TABLELIB"  ":" TABLELIB
#define TABLEAWK         "TABLEAWK"


void copytext();
void include();

extern char *getenv();

#define YY_NEVER_INTERACTIVE 1
#define YY_SKIP_YYWRAP
#define yywrap()	1

/* This YYINPUT definitions sets the scanner to traverse a string.
** The first '\0' encountered is the "EOF".
**/

static char	*tprog;


#undef  YY_INPUT
#define YY_INPUT(buf,result,max_size)   {                               \
	        if ( *buf = *tprog ) {	 				\
			tprog++;					\
                        result = 1;                                     \
                } else                                                  \
                        result = YY_NULL;                               \
        }

extern filelist	 function();
extern filelist  FileList();

extern char	*readfile();

char		*progname, *strrchr();

typedef struct Program {
	char	*buff;
	int	 leng;
	int	 here;
} Program;

typedef	struct	Arrylist {
	struct Arrylist	*next;
	char	*colnam;
	int	 colnum;
	int	 column;
} Arrylist;
	

/********************************/
/* Parser symbols and state	*/
/********************************/

char	 cnumber[40];
char	 colnam[1024];
int	 colnum;

int	StackRef = 0;

TableHead	         table = NULL, T;
static	filelist	 includes = NULL;
static	Arrylist	*arrylist = NULL;
static  Arrylist	*arryitem = NULL;

int	Napp = 0;
int	Nins = 0;
int	Nsel = 0;
char	*colapp[128];
char	*colins[128];
char	*colsel[128];
char	*prints[4096];

char	*stack = NULL;

static	Program		*program;
#line 607 "<stdout>"

#line 609 "<stdout>"

#define INITIAL 0
#define COMMENT 1
#define QUOTE 2
#define ESCAPE 3
#define HV 4
#define CV 5
#define CI 6

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 102 "table.l"

#line 840 "<stdout>"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 55 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 138 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 103 "table.l"
{ copytext(program, yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 104 "table.l"
{ copytext(program, yytext);  /* Allow ++x without invoking the +x add a column feature */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 105 "table.l"
{	/* Match possible column names		*/

		  strcpy(colnam, &yytext[1]);
		  if ( colnum = table_colnum(table, colnam) ) {
				BEGIN(CV);
		  } else {
		  	copytext(program, colnam);

			if ( *yytext == '+' ) {
			    colapp[Napp++] = strdup(colnam);
			} else {
			    colins[Nins++] = strdup(colnam);
			}
		  } 
		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 121 "table.l"
{		/* Match possible column names		*/

		  strcpy(colnam, yytext);
		  if ( colnum = table_colnum(table, colnam) ) {
				BEGIN(CV);
		  } else {
		  	copytext(program, colnam);
			/* The key word was not a column name
		   	   See if it is a header value.
		 	 */
	  		if ( table_hdrget(table, colnam, 0, 1) ) {
				BEGIN(HV);
			}
		  } 
		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 137 "table.l"
{	/* Match possible functions names	*/

				filelist fp;

		  copytext(program, yytext);
		  if ( fp = function(yytext, yyleng -1) ) {
				filelist cp;

			Malloc(cp, sizeof(struct _filelist));
			cp->next = NULL;
			cp->name = fp->name;
			cp->path = fp->path;

			includes = ListAdd(includes, cp);
		  }
		}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 154 "table.l"
{	/* The column value is indexed			*/

		  	Arrylist *al;

		  for ( al = arrylist; al; al = al->next )
			if ( !strcmp(al->colnam, colnam) ) break;
	  
		  if ( al == NULL ) {
		      New(al, Arrylist);
		      NewString(al->colnam, colnam);
		      al->colnum = -colnum;
		      al->column =  colnum;
		      al->next = arrylist;
		      arrylist = al;
		  }

		  arryitem = arrylist;

		  copytext(program, colnam);
		  copytext(program, yytext);

		  BEGIN(CI); 					}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 177 "table.l"
{	/* The column value is not indexed		*/
		  sprintf(cnumber, "$%d", colnum);
		  copytext(program, cnumber);
		  copytext(program, yytext);

		  if ( *yytext == '\"' ) { BEGIN(QUOTE);
		  } else { 		   BEGIN(INITIAL);				
		  }
		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 187 "table.l"
{ if ( arryitem->colnum < 0 ) arryitem->colnum = -arryitem->colnum;

		  copytext(program, yytext);
		  BEGIN(INITIAL); 					}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 192 "table.l"
{ copytext(program, yytext);
		  BEGIN(INITIAL); 					}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 197 "table.l"
{	/* The header value is already indexed.		*/
		  copytext(program, yytext);
		  BEGIN(INITIAL);				}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 201 "table.l"
{	/* The header value is not indexed.		*/
		  copytext(program, "[1]");
		  copytext(program, yytext);
		  if ( *yytext == '\"' ) { BEGIN(QUOTE);
		  } else {		   BEGIN(INITIAL);				
		  }
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 209 "table.l"
{ if ( stack ) {
    			StackRef = 1;
		        copytext(program, "_Stack");
		        BEGIN(HV);
		  } else {
		  	copytext(program, yytext);
		  }
		}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 218 "table.l"
{	/* Match and skip any text within comments	*/

		  copytext(program, yytext);  BEGIN(COMMENT);	}
	YY_BREAK
case 14:
/* rule 14 can match eol */
YY_RULE_SETUP
#line 221 "table.l"
{ copytext(program, yytext);  BEGIN(INITIAL);	}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 222 "table.l"
{ copytext(program, yytext);			}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 225 "table.l"
{ 	/* Match and skip any text within quotes	*/
		  copytext(program, yytext);  BEGIN(QUOTE);	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 227 "table.l"
{ copytext(program, yytext);  BEGIN(ESCAPE);	}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 228 "table.l"
{ copytext(program, yytext);  BEGIN(QUOTE);	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 229 "table.l"
{ copytext(program, yytext);  BEGIN(INITIAL);	}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 230 "table.l"
{ copytext(program, yytext);  			}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 232 "table.l"
{ 	/* Match any other text				*/

		  copytext(program, yytext);
		}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(QUOTE):
case YY_STATE_EOF(ESCAPE):
case YY_STATE_EOF(HV):
case YY_STATE_EOF(CV):
case YY_STATE_EOF(CI):
#line 237 "table.l"
{ 
		  if ( YY_START == HV ) {
			copytext(program, "[1]");
		  }
		  if ( YY_START == CV ) {
		      sprintf(cnumber, "$%d", colnum);
		      copytext(program, cnumber);
		  }
			
		  return 1;
		}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 248 "table.l"
ECHO;
	YY_BREAK
#line 1153 "<stdout>"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 55 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 55 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 54);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 248 "table.l"



void parse(txt)
     char	*txt;
{
  static int parser = 0;

  tprog= txt;

  if ( parser ) {
    yyrestart((void *)  txt);
    BEGIN(0);
  } else {
    parser = 1;
  }

  if ( !yylex() ) {
    FPrint(Stderr, "%s : can't parse program\n", progname);
    exit(1);
  }
}

void copytext(program, text)
    Program	*program;
    char	*text;
{
  while ( *text ) {
	if ( program->buff == NULL || program->here >= program->leng - 1 ) {
	    program->leng *= 2;
	    program->leng += 128;
	    ReAlloc(program->buff, program->leng);
	}

	program->buff[program->here++] = *text++;
  }
  program->buff[program->here] = '\0';
}


static filelist fpinc = NULL;
static filelist fptab = NULL;

int main(argc, argv)
     int	 argc;
     char	*argv[];
{
  int	what;
  
  static Program	 preamble = { NULL, 0, 0 };
  static Program	 prog     = { NULL, 0, 0 };
  static Program	*prep     = &preamble;

  int		 argi;
  int		 argj	 = 0;
  int		 argk;
  char		*argx[1024];
  int		 i, j;

  char		*text;
  char          *talk;

  char		*ifile = NULL;
  char		*ofile = NULL;
  char		*pfile = NULL;
  char		*head = NULL;

  char		*cols = NULL;
  int		 debug= 0;

  char		 stkval[1024];
  char		 buffer[1024];

  File		tfp = NULL;
  File		ifp = Stdin;
  File		ofp = Stdout;

  int		progarg = 0;
  int		inter   = 0;
  
  char	*tableinc;
  char	*tablefun; 


  struct stat statbuf;

  char	ncolstr[32];


typedef struct _DoWhat {
  char	*name;
  char	*prec;
  char	*post;
  int	 proc;
} DoWhat;

#define HEADER	0x0001
#define HDRVAL	0x0002
#define PRINTH	0x0004
#define PARSEH	0x0008
#define CATARG	0x0010
#define HASSTK	0x0020
#define ONEEXP	0x0040
#define ARRINP	0x0080
#define ARROUT	0x0100
#define COLSEL	0x0200

#define	TBLPRG	( HEADER | HDRVAL | PARSEH | PRINTH | ARRINP )

  static DoWhat dx[] = {
   {"reckon"	, "BEGIN { "	   , " }",		0			 }
 , {"calc"	, "BEGIN { _ANS = ", "\nprint _ANS }",	CATARG | HASSTK		 }
 , {"table"	,  NULL		   , NULL,		0			 }
 , {"row"	,  NULL		   , NULL,		TBLPRG | COLSEL | ONEEXP }
 , {"select"	,  NULL		   , NULL,		TBLPRG | COLSEL | ONEEXP }
 , {"compute"	, "{"		   , "}\n",		TBLPRG | COLSEL | ARROUT }
 , {"validate"	,  NULL		   , NULL,		TBLPRG | COLSEL	| ARROUT }
 , { NULL	,  NULL	  	   , NULL,		0			 }
};

  program = &prog;
  signal(SIGPIPE, SIG_IGN);

  if ( (progname = strrchr(argv[0], '/')) )
    progname++;
  else	progname = argv[0];

  {
	char	*binpath = strdup(argv[0]);
	char	*endpath = strrchr(binpath, '/');

	if ( endpath ) *endpath = '\0';
	else 	       *binpath = '\0';

      tableinc = malloc(strlen(binpath) + strlen(TABLEINC) + 2);
      strcpy(tableinc, TABLEINC);
      if ( *binpath ) {
	strcat(tableinc, ":");
      	strcat(tableinc, binpath);
      }
  }

  fpinc = FileList(tableinc, "*");
  if ( !((tablefun = getenv("TABLEFUN")) && *tablefun == '\0') ) {
      fptab = FileList(TABLEFUN, "*");
  }

  for ( what = 0; dx[what].name; what++ ) {
    if ( !strcmp(progname, dx[what].name) ) break;
  }

  if ( dx[what].name == NULL ) {
    FPrint(Stderr, "table : don't know how to %s\n", progname);
    exit(1);
  }

    /* Handle command line arguments
     */
    for ( argi = 1;  argi < argc && argv[argi][0] == '-'; ) {
	switch ( argv[argi++][1] ) {
          case 'f': {	int j;

	       for ( j = 2; argv[argi-1][j]; j++ ) {
	           switch ( argv[argi-1][j] ) {
		     case 'D':	debug = 1;				break;
		     case 'r':   dx[what].proc |= HEADER;		break;
		     case 'x':   dx[what].proc &= ~HDRVAL;		break;
		     case 'p':   dx[what].proc |= PRINTH;		break;
		     case 'h':	dx[what].proc |= PARSEH | HDRVAL | ARRINP | ARROUT;	break;
		   }
		}
		pfile  = argv[argi++];
		break;	
	    }
	  case 'H':	head   = argv[argi++];   		break;
	  case 'D':  debug = 1;				break;
	  case 'r':  dx[what].proc |= HEADER;		break;
	  case 'p':  dx[what].proc |= PRINTH;		break;
	  case 'h':  dx[what].proc |= PARSEH | HDRVAL;	break;
	  case 'x':  dx[what].proc &= ~HDRVAL;		break;
	  case 's':  stack = argv[argi++];		break;
	  case 'i':  ifile = argv[argi++];		break;
	  case 'I':  inter = 1;				break;
		     argi++;				break;
	  case 'o':  ofile = argv[argi++]; 		break;

	  case 'v':  if ( argj == 0 ) argj = argi-1;       
		     argi++;                            break;

	  case 'F': {
			filelist cp;

		Malloc(cp, sizeof(struct _filelist));
		cp->next = NULL;
		cp->name = argv[argi++];
		cp->path = "";

		includes = ListAdd(includes, cp);
		break;
	  }

	  default:   goto done_with_args;
	}
    }
    done_with_args:

    argk = argi;


    if ( pfile ) {
	if ( (text = readfile(pfile)) == NULL ) {
	    FPrint(Stderr, "%s : reading file %s\n", progname, pfile);
	    perror(progname);
	    exit(1);
	}
    } else {
	if ( argi >= argc ) {
	  FPrint(Stderr
		  , "%s : Usage : %s [-f source | 'cmds']\n"
		  , progname, progname);
	  exit(1);
	}

	if ( dx[what].proc & CATARG ) {
	    int	len = 0;

	  for ( i = argi; i < argc; i++ )
	    len += strlen(argv[i]) + 2;

	  Malloc(text, len);
	  text[0] = '\0';
	  for ( i = argi; i < argc; i++ ) {
	    strcat(text, argv[i]);
	    strcat(text, " ");
	  }
	  argi = argc;
	} else {
	  if ( dx[what].proc & COLSEL ) {
	      while ( argi < argc - 1 ) {
		  colsel[Nsel++] = argv[argi++];
	      }
	  } 

	  /* Malloc(text, strlen(argv[argc-1])) + 2; */
	  text = argv[argc-1];
	  argc--;
	}

	if ( dx[what].proc & ONEEXP ) {
	  for ( i = 0; text[i]; i++ ) {
	    if ( text[i] == '\n' || text[i] == '\r' ) { text[i] = ' '; }
	  }
	}
    }

      if ( head || dx[what].proc & PRINTH || dx[what].proc & PARSEH ) 
	    dx[what].proc |= HEADER;

      if ( head ) {
	    if ( (tfp = Open(head, "r")) == NULL ) {
	      FPrint(Stderr, "%s: can't open header reference file: %s\n", progname, head);
	      exit(1);
	    }
      }

      if ( ifile ) {
	    if ( (ifp = Open(ifile, "r")) == NULL ) {
	      FPrint(Stderr, "%s: can't open input file: %s\n", progname, ifile);
	      exit(1);
	    }
      }
      SetBuffer(ifp, FileNullBuffer, NULL, 0);

      if ( ofile ) {
	    if ( (ofp = Open(ofile, "w")) == NULL ) {
	      FPrint(Stderr, "%s: can't open input file: %s\n", progname, ofile);
	      exit(1);
	    }
      }

      if ( dx[what].proc & HASSTK && stack == NULL && getenv("HOME") != NULL ) {
	    stack = stkval;
	    sprintf(stkval, "%s/.calc", getenv("HOME"));
      }

      {
		filelist fp;
		char	path[2048];
		char	*text;
		int		gotinc = 0;

	    for ( fp = fpinc; fp; fp = ListNext(fp) ) {
		if ( !strcmp(fp->name, ".table") ) {
		    strcpy(path, fp->path);
		    strcat(path, "/");
		    strcat(path, fp->name);

		    if ( text = readfile(path) )
			copytext(prep, text);
		}
		if ( !gotinc ) {
		    if ( !strcmp(fp->name, "table.inc") ) {
			strcpy(path, fp->path);
			strcat(path, "/");
			strcat(path, fp->name);

			if ( text = readfile(path) ) {
			    copytext(prep, text);
			    gotinc = 1;
			}
		    }
		}
	    }
      }


      /* Output the initial BEGIN clause to set thing up
       */
      copytext(prep, "BEGIN {\n"	);
	
      /* Read in Header, Headline/Wideline
       */
      if ( dx[what].proc & HEADER ) {
	if ( tfp == NULL ) tfp = ifp;

	if ( (table = T = table_header(tfp, 0)) == NULL ) {
	  FPrint(Stderr, "%s : can't read table header from input\n", progname);
	  exit(1);
	}
	if ( T && !(T->mode & TABLE_NICETAB) )
	  copytext(prep, "\tFS=OFS=\"\t\"\n");

	copytext(prep, "\tHeader=\""	);
	for ( i = 1; i < table->header->ncol; i++ ) {
	  copytext(prep, table->header->column[i]);
	  copytext(prep, "\t");
	}
	copytext(prep, table->header->column[i]);
	copytext(prep, "\"\n");
	copytext(prep, "\tDashes=\""	);
	for ( i = 1; i < table->dashes->ncol; i++ ) {
	  copytext(prep, table->dashes->column[i]);
	  copytext(prep, "\t");
	}
	copytext(prep, table->dashes->column[i]);
	copytext(prep, "\"\n");

	if ( table->name ) {
	  copytext(prep, "\tTableName=\"");
	  copytext(prep, table->name);
	  copytext(prep, "\"\n\n");
	}

	  copytext(prep, "\tNValues=");
	  sprintf(buffer, "%d\n\n", table->nvalue);
	  copytext(prep, buffer);


	  if ( dx[what].proc & HDRVAL ) {
	    /* Set up the header values
	     */
	    for ( i = 0; i < table->nvalue; i++ ) {
	     if ( table->values[i]->column[1][0] != '\0' ) {
		    char *colid = table->values[i]->column[1];

		       if ( *colid == '#' ) colid++;
		    while ( *colid == ' ' ) colid++;

	      if ( table->values[i]->ncol >= 2 
		&& table_isid(colid) ) {

		copytext(prep, "\t");
		copytext(prep, "N_");
		copytext(prep, colid);
		copytext(prep, " = split(\"");
		for ( j = 2; j < table->values[i]->ncol; j++ ) {
		    copytext(prep, table->values[i]->column[j]);
		    if ( table->values[i]->ncol > 2 ) copytext(prep, "\t");
		}
		copytext(prep, table->values[i]->column[j]);
		copytext(prep, "\", ");
		
		copytext(prep, colid);
		copytext(prep, ")\n");
	      }
	     }
	    }
	  }
      }

      copytext(prep, "}\n");


      /* disable the $column text replacement.
       */
      if ( !(dx[what].proc & PARSEH) ) {
	    table = NULL;
      }

      /* Process awk program text
       */
      if ( dx[what].prec ) copytext(program, dx[what].prec);
      parse(text);
      if ( dx[what].post ) copytext(program, dx[what].post);

      if ( !StackRef ) { stack = NULL; }

      if ( stack && !stat(stack, &statbuf) ) {
	copytext(prep, "\nBEGIN {\n");
	copytext(prep, " stack = \""); copytext(prep, stack); copytext(prep, "\"\n");
	copytext(prep, " for ( i = 1; getline v < stack > 0; i++ )\n");
	copytext(prep, "  _Stack[i] = v\n");
	copytext(prep, " _Stack[0] = i;\n");
	copytext(prep, " i = \"\"; v = \"\"; stack = \"\"\n");
	copytext(prep, "}\n");
      }

      if ( dx[what].proc & ARRINP >= 2 && arrylist ) {
	    Arrylist	*al;

	  copytext(prep, "{\n");
	  for ( al = arrylist; al; al = al->next ) {
		    char	cnumber[32];
	    copytext(prep, "\tN_"); copytext(prep, al->colnam);
	    copytext(prep, " = split($");
	    sprintf(cnumber, "%d", al->column);
	    copytext(prep, cnumber); 
	    copytext(prep, ", ");
	    copytext(prep, al->colnam);
	    copytext(prep, ", ARRDEL)\n");
	  }
	  copytext(prep, "\n}\n");
      }

      if ( T && T->mode & TABLE_NICETAB ) {
	    copytext(prep, "\n/^[ 	]*$/ {\texit\t}\n");
      }

      copytext(prep, program->buff);
      program = prep;


  if ( dx[what].proc & ARROUT && arrylist ) {
	Arrylist	*al;
	int		 output = 0;


      for ( al = arrylist; al; al = al->next ) {
	if ( al->colnum > 0 ) {
		    char	cnumber[32];

      	    if ( !output ) copytext(prep, "{\n");
	    output = 1;

	    copytext(prep, "\t_a = ");
	    copytext(prep, al->colnam);
	    copytext(prep, "[1]; for ( _i = 2; _i <= N_");
	    copytext(prep, al->colnam);
	    copytext(prep, "; _i++ ) _a = _a ARRDEL ");
	    copytext(prep, al->colnam);
	    copytext(prep, "[_i]; $");
	    sprintf(cnumber, "%d", al->column);
	    copytext(prep, cnumber); 
	    copytext(prep, " = _a\n");
	}
      }
      if ( output ) copytext(prep, "\n}");
  }
  if ( dx[what].proc & COLSEL ) {
	copytext(prep, " { ");
	copytext(prep, "print ");

	for ( i = 0; i < Nins; i++ ) {
	    copytext(prep, colins[i]);
	    copytext(prep, ", ");
	}

	if ( Nsel ) {
	    for ( i = 0; i < Nsel; i++ ) {
		int col = table_colnum(T, colsel[i]);

		if ( col ) {
		    char name[256];

		    sprintf(name, "$%d", col);
		    copytext(prep, name);
		    if ( i < Nsel-1 ) copytext(prep, ", ");
		} else {
		    copytext(prep, colsel[i]);
		    if ( i < Nsel-1 ) copytext(prep, ", ");

		    table_coladd(T, colsel[i]);
		} 
	    }
	} else {
	    copytext(prep, "$0");
	}
	for ( i = 0; i < Napp; i++ ) {
	    copytext(prep, ", ");
	    copytext(prep, colapp[i]);
	}
	copytext(prep, " }\n");
  }

  /* Process any included functions
   */
  table = NULL;		/* This disables the $column text
			 * replacement in the parser	*/
  include();


  if ( stack && !stat(stack, &statbuf) ) {
    copytext(prep, "\nBEGIN {\n");
    copytext(prep, " stack = \""); copytext(program, stack); copytext(program, "\"\n");
    copytext(prep, " print _ANS > stack\n");
    copytext(prep, " _Stack[0]--\n");
    copytext(prep, " for ( i = 1; i < _Stack[0]; i++ )\n");
    copytext(prep, "  print _Stack[i] > stack\n");
    copytext(prep, "}\n");
  }

  /* Construct awk command
   */
  (talk = getenv(TABLEAWK)) == NULL && (talk = "tawk");

  j = 0;
  argx[j++]	= dx[what].name;

  if ( T && T->mode & TABLE_NICETAB ) {
      sprintf(ncolstr, "%d", T->header->ncol);
      argx[j++]     = "-C";
      argx[j++]     = ncolstr;
  }

  if ( inter ) {
      argx[j++]     = "-W";
      argx[j++]     = "interactive";
  }
  if ( arrylist ) {
      argx[j++]	    = "-v";
      argx[j++]	    = "ARRDEL= ";
  }


  if ( argj ) {
      for ( i = argj; i < argk; i++ ) 
	    if ( argv[i][0] ) argx[j++] = argv[i];
  }

  progarg = j;
  argx[j++]	= prep->buff;

  for ( i = argi; i < argc; i++ ) 
	if ( argv[i][0] ) argx[j++] = argv[i];
  argx[j] = NULL;

  if ( debug ) {
    FPrint(Stderr, "#!/bin/sh\n#\n\n mawk ");
    for ( i = 0; i < j; i++ ) {
      if ( i == progarg ) FPrint(Stderr, "'\n");
      FPrint(Stderr, "%s ", argx[i]);
      if ( i == progarg ) FPrint(Stderr, "'\n");
    }
  }

  if ( dx[what].proc & PRINTH ) {
	int	 Ncol   = table_ncol(T);
	int	*select = malloc((Nins + Napp + Ncol + 1) * sizeof(int *));

    i = 0;
    for ( j = 0; j <  Nins; j++ ) {
	int col = table_colnum(T, colins[j]);

	if ( col ) select[++i] = col;
	else       select[++i] = table_coladd(T, colins[j]);
    }
    if ( Nsel ) {
	for ( j = 0; j <  Nsel; j++ ) { select[++i] = table_colnum(T, colsel[j]); }
    } else {
	for ( j = 1; j <= Ncol; j++ ) { select[++i] = j; }
    }
    for ( j = 0; j <  Napp; j++ ) {
	int col = table_colnum(T, colapp[j]);

	if ( col ) select[++i] = col;
	else       select[++i] = table_coladd(T, colapp[j]);
    }

    table_hdrput(ofp, T, 0, NULL, select, i);
    Flush(ofp);
  }

  dup2(FileFd(ifp), 0);
  dup2(FileFd(ofp), 1);
  execvp(talk, argx);
  perror(progname);
  fprintf(stderr, "error trying to exec : %s\n", talk);
  exit(1);
}



filelist function(yytext, yyleng)
			char	*yytext;
			int	 yyleng;
{
		filelist	fp;


	for ( fp = fptab; fp; fp = ListNext(fp) ) {
	    if ( strlen(fp->name) == yyleng
	     && !strncmp(yytext, fp->name, yyleng) ) break;
	}

	if ( fp != NULL && !fp->mark ) {
		fp->mark = 1;
		return fp;
	} else	return NULL;
}

void include()
{
	char            funct[1024]; char            *text;

	for ( ; includes; includes = ListPop(includes) ) {
		funct[0] = '\0';

		if ( includes->path[0] ) {
		    strcpy(funct, includes->path);
		    strcat(funct, "/");
		}
		strcat(funct, includes->name);

		copytext(program, "\n");

		if ( text = readfile(funct) ) {
			parse(text);
			Free(text);
		} else {
			fprintf(stderr, "%s : could not read include file %s\n"
				      , progname, funct);
		}
	}
}


