#!/bin/sh
#
# tabletolatex
#
# Starbase Data Tables  - An Ascii Database for UNIX
#
#   copyright 1991, 1993, 1995, 1999 John B. Roll jr.
#   
PATH=.:/bin:/usr/bin;	export PATH

trap "" 13

 while [ $# -ge 1 ] ; do
  case $1 in 
   -i) shift; ifile=$1					;;
   -o) shift; ofile=$1					;;
   -j) shift; just=$1                                   ;;
   -c) shift; capt=$1                                   ;;
    *) if [ "$ifile" = "" ] ; then
	ifile=$1
       else
	echo "usage: tabletolist [[-i] ifile] [-o ofile] [-j justification] [-c caption]"
	exit 1;
       fi
       ;;
  esac
  shift
 done

 if [ "$ifile" != "" ] ; then
	exec < $ifile
 fi
 if [ "$ofile" != "" ] ; then
	exec > $ofile
 fi

tawk -v "justification=$just" -v "caption=$capt" '
BEGIN {  FS="	"
	OFS="	"
	ncol = table_header(V, C, D)

	print ""
	if (justification == "") {
	    for ( i = 1; i <= ncol; i++ ) {
		justification=justification "c"
	    }
   	}
	print "\\begin{deluxetable}{" justification "}"
	print "\\tablecaption{" caption "}"
	print "\\tablehead{"
	amp = "&"
	for ( i = 1; i <= ncol; i++ ) {
	        if ( i == ncol ) amp=""
		print "  \\colhead{" C[i] "} " amp
	}
	print "}"
	print "\startdata"
	eol = "\n"
}
{
	
	amp = "& "
	printf eol
	for ( i = 1; i <= ncol; i++ ) {
	        if (i==ncol) {amp = ""}
		printf  $i " " amp
	}
	eol = "\\\\\n"
}
END {
    print "\n\\enddata"
    print "\\end{deluxetable}"
}

function table_header(V, C, D,		header, dashes)
{
	getline	header
	getline	dashes
	if ( dashes !~ /(-+\t)*(-+)/ ) {
	     do {
		header = dashes	
	     } while ( getline dashes > 0 && dashes !~ /(-+\t)*(-+)/ )
	}

	n = split(header, C, /\t/)
	n = split(dashes, D, /\t/)

	return n
} '


