#!/bin/sh
#
# tactable
#
# Starbase Data Tables  - An Ascii Database for UNIX
#
#   copyright 1991, 1993, 1995, 1999 John B. Roll jr.
#   
#
PATH=.:/bin:/usr/bin;	export PATH

trap "" 13

cat | (
	header -u
	tac
)
