#!/usr/bin/perl
#

use lib "/home/john/src/tcl/perl/lib";
#use strict;

if(!(defined $ARGV[0])) {
    print<<EOF;
Usage: $0 Excel_File
EOF
    exit;
}
use Spreadsheet::ParseExcel;
my $oExcel = new Spreadsheet::ParseExcel;
my $oBook = $oExcel->Parse($ARGV[0]);

my($oWkS, $oWkC);

for ( my $i = 1; $i < @ARGV; $i++ ) {
 my @Sheet = split(":", $ARGV[$i]);
 my $file  = "STDOUT";

 foreach my $oWkS (@{$oBook->{Worksheet}}) {
  if ( $Sheet[0] eq "" || $Sheet[0] eq $oWkS->{Name} ) {
    if ( defined @Sheet[6] && $Sheet[6] ne "" ) {
        $file = $Sheet[6];
        open($file, ">$file") || die ": can't open file $file\n";
    } else {
	$file = "STDOUT";
    }

    my ( $x1, $x2, $y1, $y2 );

	$x1 = 0;
	$x1 = @Sheet[1] if defined @Sheet[1] && $Sheet[1] ne "";
 
	$x2 = $oWkS->{MaxCol};
	$x1 = @Sheet[2] if defined @Sheet[2] && $Sheet[2] ne "";
	$y1 = 0;
	$x1 = @Sheet[3] if defined @Sheet[3] && $Sheet[3] ne "";
	$y2 = $oWkS->{MaxRow};
	$x1 = @Sheet[4] if defined @Sheet[4] && $Sheet[4] ne "";

    print $file $oWkS->{Name}, "\n\n";
    if ( !defined @Sheet[5] || $Sheet[5] =~ /H/ ) {
      for( my $x = $x1 ; $x <= $x2 ; $x++) {
        my $cell = $oWkS->{Cells}[$y1][$x] ;
	my $valu;
	if ( defined $cell ) {
	    $valu = $cell->Value;

	    $valu =~ s/[ .\$]//g;
	    $valu =~ s/[^a-zA-Z0-9_]/_/g;
	} else {
	    $valu = $x;
	}
        print $file $valu;
        print $file "\t" if( $x != $x2) ;
      }
      print $file "\n" ;
    }
    if ( !defined @Sheet[5] || $Sheet[5] =~ /D/ ) {
      for( my $x = $x1 ; $x <= $x2 ; $x++) {
        print $file "-";
        print $file "\t" if( $x != $x2) ;
      }
    }

    $y1++;
    print $file "\n" ;
    for( my $y = $y1 ; $y <= $y2 ; $y++) {
        for( my $x = $x1 ; $x <= $x2 ; $x++) {
            my $cell = $oWkS->{Cells}[$y][$x] ;
            print $file $cell->Value if(defined $cell);
            print $file "\t" if( $x != $x2) ;
        }
        print $file "\n" ;
    }
  }
 }
}
