# These are the default definitions for all starbase makefiles
#

srcdir	= .
 
AR 	= ar
INC     = $(WD)/tablesrc/xinc
LEX     = flex
LN_S    = ln -s
SED     = sed
RANLIB 	= ranlib
RM      = rm -f
YACC 	= bison -y

exeext	= ""

MAKEDEFS = bindir=$(bindir) libdir=$(libdir) incdir=$(incdir)

Arch	  = `uname`-`uname -i`

