#!/bin/sh
#
# fk524
#
# Starbase Data Tables  - An Ascii Database for UNIX
#
#   copyright 1991, 1993, 1995, 1999 John B. Roll jr.
#
#   
PATH=.:/bin:/usr/bin;	export PATH

TABLELIB=$TABLELIB;  export TABLELIB
TABLEFUN="";  export TABLEFUN

 while [ $# -ge 1 ] ; do
  case "$1" in 
   -i) shift; ifile="$1"				;;
   -o) shift; ofile="$1"				;;
   -*) echo "fk524: unknown option"; exit 1		;;
    *) argv="$argv $1"					;;
  esac
  shift
 done

 if [ "$ifile" != "" ] ; then
	exec < $ifile
 fi

 if [ "$ofile" != "" ] ; then
	exec > $ofile
 fi

table -p $argv '
BEGIN {
	Init = 0

	rcol 	= "ra"
	dcol 	= "dec"

	paramcheck("fk524", "rcol|dcol|rdcol|ddcol|par|vel")
}
!Init {	__r = table_colnum(rcol)
	__d = table_colnum(dcol)
	_rd = table_colnum(rdcol)
	_dd = table_colnum(ddcol)
	_pr = table_colnum(par)
	_vl = table_colnum(vel)

	if ( !__r )	printf("fk524: no column \"%s\".\n", rcol) > "/dev/stderr"
	if ( !__d )	printf("fk524: no column \"%s\".\n", dcol) > "/dev/stderr"
	if ( !__r || !__d ) {
		exit 1
	}

	Init = 1
}
{	if ( _rd && _dd && _pr && _vl ) {
	    [ $__r, $__d, $_rd, $_dd, $_pr, $_vl ] = fk524($__r, $__d, $_rd, $_dd, $_pr, $_vl);
	} else {
	  if ( _rd && _dd ) {
	    [ $__r, $__d, $_rd, $_dd ] = fk524($__r, $__d, $_rd, $_dd, 0, 0);
	  } else {
	    [ $__r, $__d ] = fk524($__r, $__d, 0, 0, 0, 0);
	  }
	}

	print }

include ../tablefun/paramcheck 
include ../tablefun/table_colnum 

 '
