#!/bin/sh
#
# s2tptable
#
# Starbase Data Tables  - An Ascii Database for UNIX
#
#   copyright 1991, 1993, 1995, 1999 John B. Roll jr.
#
PATH=.:/bin:/usr/bin;	export PATH

TABLELIB=$TABLELIB;  export TABLELIB
TABLEFUN="";  export TABLEFUN

 while [ $# -ge 1 ] ; do
  case $1 in 
   -i) shift; ifile=$1					;;
   -o) shift; ofile=$1					;;
   -D) DEBUG=-D						;;
   -*) echo "tp2stable: unknown option"; exit 1		;;
    *) argv="$argv $1"					;;
  esac
  shift
 done

 if [ "$ifile" != "" ] ; then
	exec < $ifile
 fi

 if [ "$ofile" != "" ] ; then
	exec > $ofile
 fi

table -p $DEBUG $argv '
BEGIN {
	Init = 0

	rcol 	 = "RA"
	dcol 	 = "Dec"
	rotation = 0
	scale    = 1

	paramcheck("s2tptable", "rcol|dcol|xcol|ycol|zra|zdec|rotation|scale")
}
!Init {	__r = table_colnum(rcol)
	__d = table_colnum(dcol)

	if ( !__r )	printf("s2tptable: no column \"%s\".\n", rcol) > "/dev/stderr"
	if ( !__d )	printf("s2tptable: no column \"%s\".\n", dcol) > "/dev/stderr"

       	__x = table_colnum(xcol)
	__y = table_colnum(ycol)

	if ( !__x )	__x = __r
	if ( !__y )	__y = __d

	if ( zra == "" ) printf("s2tptable: RA zero point\n")  > "/dev/stderr"
	if ( zdec== "" ) printf("s2tptable: Dec zero point\n") > "/dev/stderr"
	if ( !__r || !__d || zra == "" || zdec == "" ) {
		exit 1
	}

	Init = 1
}
{	[ $__x, $__y ] = s2tp($__r, $__d, zra, zdec, scale, rotation); print }

include ../tablefun/paramcheck 
include ../tablefun/table_colnum 

 '
