name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref_name }} \
          --title "Release ${{ github.ref_name }}" \
          --generate-notes

  build-and-upload:
    needs: create-release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@main
    
    - name: Build
      shell: bash
      run: |
        ./configure
        make release
    
    - name: Move artifacts
      shell: bash
      run: |
        mv ../*.tgz .
        mv ../*.zip .
    
    - name: Upload Release Assets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: |
        for file in *.tgz *.zip
        do
          gh release upload ${{ github.ref_name }} "$file" --clobber
        done

    - name: List artifacts (for debugging)
      shell: bash
      run: ls -l *.tgz
